### ISSUE TITLE
R.layout.item_nearbydialog文件缺失

### ISSUE THREAD

**Issue by liuhaifang** [XXQAQ/FasterDialog#2]
![image](https://user-images.githubusercontent.com/7792028/59583311-78468280-910d-11e9-81cd-3bc240a43a80.png)

**Comment by XXQAQ** [comment]
这个layout只是我个人示例，项目中存在一些默认布局文件，你也可以传入你自己在项目中定义的布局文件，FasterDialog会直接以你传入的布局显示
