### ISSUE TITLE
BaseEditDialog中获取不到EditText

### ISSUE THREAD

**Issue by maweiyue** [XXQAQ/FasterDialog#3]
### 使用EditDialog，添加7个InputBean。在dialog.show()的时候，空指针异常。
InputBean xyjinrufengzhi = new InputBean();
InputBean zjinrufengzhi = new InputBean();
InputBean panduanmoshi = new InputBean();
InputBean xyyouchefazhi = new InputBean();
InputBean zuidayouchefazhi = new InputBean();
InputBean youchepanduanfangshi = new InputBean();
InputBean fudongfengzhi = new InputBean();
InputBean[] jinrucanshu = new InputBean[]{xyjinrufengzhi, zjinrufengzhi, panduanmoshi, 
xyyouchefazhi,zuidayouchefazhi, youchepanduanfangshi, fudongfengzhi};
EditDialog dialog = new EditDialog(getActivity())
            .setTitle(title)
            .setPositiveText("确定")
            .setOnEditCompletedListener(new BaseEditDialog.OnEditCompletedListener() {
            @Override
            public void onEditCompleted(BaseEditDialog dialog, SparseArray<CharSequence> array) {
            }
        })
        .setNegativeText("取消");
for (int i = 0; i < inputBeans.length; i++) {
       dialog.setInputBean(i, inputBeans[i]);
}
dialog.show();

报错代码：
BaseEditDialog->onCreate()，for循环到index=3的时候，获取到的editText为null了。
EditText editText = findViewById(getContext().getResources().getIdentifier("edit_" + key, "id", getContext().getPackageName()));
此处editText是null。

不知道是何原因？

**Comment by XXQAQ** [comment]
官方默认布局只有三个EditText，你的描述属于高定制化布局方案，建议使用你自己定义的布局，通过setCustomView(R.layout.yourlayout)传入你自己的布局方案，唯一需要注意的是你布局中的控件id需要与项目中的id协定一致
![image](https://user-images.githubusercontent.com/25736313/60239496-87cd8480-98e0-11e9-90cc-a66268c5f80c.png)
