### ISSUE TITLE
指定的控ID

### ISSUE THREAD

**Issue by panghu852** [XXQAQ/FasterDialog#4]
本框架指定控件Id是什么，在哪显示了

**Comment by XXQAQ** [comment]
目前没有专门的文档进行描述，使用的时候需要追寻到源代码中阅读，像这样
![image](https://user-images.githubusercontent.com/25736313/60239452-5b196d00-98e0-11e9-8db3-2a74cd94f122.png)

**Comment by panghu852** [comment]
了解

**Comment by XXQAQ** [comment]
> 了解

我正在完善FasterDialog库中，完善以后就会撰写文档。如果你对本项目有自己的见解或者有完善项目的建议，可以与我联系。争取让它成为Android平台上最好用的Dialog框架，让项目不需要再依赖其他任何三方弹窗开源框架

**Comment by panghu852** [comment]
好嘞，有问题会提
