### ISSUE TITLE
兄弟，listdialog 没数据插入方法么

### ISSUE THREAD

**Issue by wrz123456** [XXQAQ/FasterDialog#5]
ItemBehavior 这个是啥子

**Comment by XXQAQ** [comment]
> ItemBehavior 这个是啥子

首先，Behavior是个接口，用于描述一类对象的行为。对于ListDialog来说，ItemBehavior代表其每一个Item的所要描述的内容，例如 标题 ，图标 选中状态等等。如果你需要让自己的JavaBean直接在ListDialog中显示，则实现ItemBehavior 即可。普通情况下，也可以直接使用我定制的对象——ItemBean，ItemBean默认实现了ItemBehavior 接口

**Comment by XXQAQ** [comment]
> ItemBehavior 这个是啥子

setItemList这个方法还有一个重载，在传入true的话即代表数据是追加的，传入false则表示新数据会覆盖旧数据
