### ISSUE TITLE
如何给自定义layout内的控件设定点击事件？

### ISSUE THREAD

**Issue by Huongzer** [XXQAQ/FasterDialog#7]
我是初学者，看到您的库非常好用，可就是有这个问题。我在里面发现了个setClickListener设定点击监听，但是不知道怎么使用？

**Comment by XXQAQ** [comment]
外界只需要调用setPositiveListener或者setNegativeListener或者setNeutralListener即可；以上方法最终都是调用的setClickListener方法，setClickListener这个方法是个私有方法，对回调进行了一步封装，外部调用者通常不需要关心setClickListener这个方法

**Comment by Huongzer** [comment]
您好！ 由于这是系统自动发信，所以请勿对此信件进行回复！
有什么问题可以联系站长QQ：439498
