### ISSUE TITLE
EditDialog里EditText没有直接设置高度的方法？

### ISSUE THREAD

**Issue by snintelligent** [XXQAQ/FasterDialog#8]
有的输入不止一行，重新写布局也是可以的...最好还是提供一下吧

**Comment by XXQAQ** [comment]
emm，原则来说，每个项目的弹窗风格样式应该都是项目自己的布局layout，所以FasterDialog没有处理任何跟UI相关的内容，是希望调用者传入自己项目的layout以指定UI。如果有这个需要，我这边可以提供一些方法以处理
