### ISSUE TITLE
AndroidFaster和WorldBean 无权限访问

### ISSUE THREAD

**Issue by wujun2081** [XXQAQ/FasterDialog#9]
作者你好。我一直在用你的这个[FasterDialog]框架。最近发现框架下的两个依赖包无权访问了。麻烦作者能不能开放一下。十分感谢。
为：com.github.XXQAQ:AndroidFaster:3.29.0 和 com.github.XXQAQ:WorldBean:1.20.0。
感谢大佬。

**Comment by XXQAQ** [comment]
你这边使用的是哪个版本，我这边已经下掉了其他的依赖

**Comment by wujun2081** [comment]
最新的版本。不过我现在更换了已经发自我的手机-------- 原始邮件 --------发件人： XXQQ ***@***.***>日期： 2023年12月20日周三 19:59收件人： XXQAQ/FasterDialog ***@***.***>抄送： 吴俊 ***@***.***>, Author ***@***.***>主    题： Re: [XXQAQ/FasterDialog] AndroidFaster和WorldBean 无权限访问 (Issue #9)
你这边使用的是哪个版本，我这边已经下掉了其他的依赖

**Comment by XXQAQ** [comment]
你是自己替换了里面缺失的那几个工具类和entity类是吗？

**Comment by wujun2081** [comment]
不是。我换了别的加载框架了。我不清楚你的依赖的写法发自我的手机-------- 原始邮件 --------发件人： XXQQ ***@***.***>日期： 2023年12月21日周四 14:00收件人： XXQAQ/FasterDialog ***@***.***>抄送： 吴俊 ***@***.***>, Author ***@***.***>主    题： Re: [XXQAQ/FasterDialog] AndroidFaster和WorldBean 无权限访问 (Issue #9)
你是自己替换了里面缺失的那几个工具类和entity类是吗？

**Comment by XXQAQ** [comment]
好的，谢谢你的提醒，我这边会把不必要的依赖去掉后提交

**Comment by idea-turtle** [comment]
我也遇到这个了 两年没有弄项目 突然发现AndroidFaster和WorldBean没办法下载了😂

**Comment by XXQAQ** [comment]
> 我也遇到这个了 两年没有弄项目 突然发现AndroidFaster和WorldBean没办法下载了😂

已处理，最新1.40.0版本剔除了不需要关心的依赖库
